export enum MovementType {
  TRANSFER = 'TRANSFER',
  PROMOTION = 'PROMOTION',
  DEMOTION = 'DEMOTION',
  LATERAL_MOVE = 'LATERAL_MOVE',
  DEPARTMENT_CHANGE = 'DEPARTMENT_CHANGE',
  BRANCH_CHANGE = 'BRANCH_CHANGE',
}
