export const CONSTANTS_LOG_ACTION = {
  /**
   * 201-files
   */
  //#region 201-files
  /** barangay */
  CREATE_BARANGAY: 'CREATE_BARANGAY',
  UPDATE_BARANGAY: 'UPDATE_BARANGAY',
  SOFT_DELETE_BARANGAY: 'SOFT_DELETE_BARANGAY',

  /** address city */
  CREATE_CITY: 'CREATE_CITY',
  UPDATE_CITY: 'UPDATE_CITY',
  SOFT_DELETE_CITY: 'SOFT_DELETE_CITY',
  /** address province */
  CREATE_PROVINCE: 'CREATE_PROVINCE',
  UPDATE_PROVINCE: 'UPDATE_PROVINCE',
  SOFT_DELETE_PROVINCE: 'SOFT_DELETE_PROVINCE',
  /** branch */
  CREATE_BRANCH: 'CREATE_BRANCH',
  UPDATE_BRANCH: 'UPDATE_BRANCH',
  SOFT_DELETE_BRANCH: 'SOFT_DELETE_BRANCH',
  /** citizenship */
  CREATE_CITIZENSHIP: 'CREATE_CITIZENSHIP',
  UPDATE_CITIZENSHIP: 'UPDATE_CITIZENSHIP',
  SOFT_DELETE_CITIZENSHIP: 'SOFT_DELETE_CITIZENSHIP',
  /** empstatus */
  CREATE_EMPSTATUS: 'CREATE_EMPSTATUS',
  UPDATE_EMPSTATUS: 'UPDATE_EMPSTATUS',
  SOFT_DELETE_EMPSTATUS: 'SOFT_DELETE_EMPSTATUS',
  /** jobtitle */
  CREATE_JOBTITLE: 'CREATE_JOBTITLE',
  UPDATE_JOBTITLE: 'UPDATE_JOBTITLE',
  SOFT_DELETE_JOBTITLE: 'SOFT_DELETE_JOBTITLE',
  /** religion */
  CREATE_RELIGION: 'CREATE_RELIGION',
  UPDATE_RELIGION: 'UPDATE_RELIGION',
  SOFT_DELETE_RELIGION: 'SOFT_DELETE_RELIGION',
  /** civilstatus */
  CREATE_CIVILSTATUS: 'CREATE_CIVILSTATUS',
  UPDATE_CIVILSTATUS: 'UPDATE_CIVILSTATUS',
  SOFT_DELETE_CIVILSTATUS: 'SOFT_DELETE_CIVILSTATUS',
  /** edu */
  CREATE_EDU: 'CREATE_EDU',
  UPDATE_EDU: 'UPDATE_EDU',
  SOFT_DELETE_EDU: 'SOFT_DELETE_EDU',
  /** edu_course */
  CREATE_EDUCOURSE: 'CREATE_EDUCOURSE',
  UPDATE_EDUCOURSE: 'UPDATE_EDUCOURSE',
  SOFT_DELETE_EDUCOURSE: 'SOFT_DELETE_EDUCOURSE',
  /** edu_courselevel */
  CREATE_EDUCOURSELEVEL: 'CREATE_EDUCOURSELEVEL',
  UPDATE_EDUCOURSELEVEL: 'UPDATE_EDUCOURSELEVEL',
  SOFT_DELETE_EDUCOURSELEVEL: 'SOFT_DELETE_EDUCOURSELEVEL',
  /** edu_level */
  CREATE_EDULEVEL: 'CREATE_EDULEVEL',
  UPDATE_EDULEVEL: 'UPDATE_EDULEVEL',
  SOFT_DELETE_EDULEVEL: 'SOFT_DELETE_EDULEVEL',
  /** edu_school */
  CREATE_EDUSCHOOL: 'CREATE_EDUSCHOOL',
  UPDATE_EDUSCHOOL: 'UPDATE_EDUSCHOOL',
  SOFT_DELETE_EDUSCHOOL: 'SOFT_DELETE_EDUSCHOOL',
  /** department */
  CREATE_DEPARTMENT: 'CREATE_DEPARTMENT',
  UPDATE_DEPARTMENT: 'UPDATE_DEPARTMENT',
  SOFT_DELETE_DEPARTMENT: 'SOFT_DELETE_DEPARTMENT',

  /** training_cert */
  CREATE_TRAININGCERT: 'CREATE_TRAININGCERT',
  UPDATE_TRAININGCERT: 'UPDATE_TRAININGCERT',
  SOFT_DELETE_TRAININGCERT: 'SOFT_DELETE_TRAININGCERT',
  /** training */
  CREATE_TRAINING: 'CREATE_TRAINING',
  UPDATE_TRAINING: 'UPDATE_TRAINING',
  SOFT_DELETE_TRAINING: 'SOFT_DELETE_TRAINING',

  /** workexp */
  CREATE_WORKEXP: 'CREATE_WORKEXP',
  UPDATE_WORKEXP: 'UPDATE_WORKEXP',
  SOFT_DELETE_WORKEXP: 'SOFT_DELETE_WORKEXP',
  /** workexp_company */
  CREATE_WORKEXPCOMPANY: 'CREATE_WORKEXPCOMPANY',
  UPDATE_WORKEXPCOMPANY: 'UPDATE_WORKEXPCOMPANY',
  SOFT_DELETE_WORKEXPCOMPANY: 'SOFT_DELETE_WORKEXPCOMPANY',
  /** workexp_jobtitle */
  CREATE_WORKEXPJOBTITLE: 'CREATE_WORKEXPJOBTITLE',
  UPDATE_WORKEXPJOBTITLE: 'UPDATE_WORKEXPJOBTITLE',
  SOFT_DELETE_WORKEXPJOBTITLE: 'SOFT_DELETE_WORKEXPJOBTITLE',
  /** reference */
  CREATE_REFERENCE: 'CREATE_REFERENCE',
  UPDATE_REFERENCE: 'UPDATE_REFERENCE',
  SOFT_DELETE_REFERENCE: 'SOFT_DELETE_REFERENCE',

  /** employee */
  UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
  CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
  UPDATE_EMPLOYEE_IMAGE_PATH: 'UPDATE_EMPLOYEE_IMAGE_PATH',
  UPDATE_EMPLOYEE_GOVERNMENT_DETAILS: 'UPDATE_EMPLOYEE_GOVERNMENT_DETAILS',
  UPDATE_EMPLOYEE_END_DATE: 'UPDATE_EMPLOYEE_END_DATE',
  FIND_EMPLOYEE_BY_ID: 'FIND_EMPLOYEE_BY_ID',

  /** employee_movement */
  CREATE_EMPLOYEE_MOVEMENT: 'CREATE_EMPLOYEE_MOVEMENT',
  UPDATE_EMPLOYEE_MOVEMENT: 'UPDATE_EMPLOYEE_MOVEMENT',
  APPROVE_EMPLOYEE_MOVEMENT: 'APPROVE_EMPLOYEE_MOVEMENT',
  SOFT_DELETE_EMPLOYEE_MOVEMENT: 'SOFT_DELETE_EMPLOYEE_MOVEMENT',
  /** employee_movement_type */
  CREATE_EMPLOYEE_MOVEMENT_TYPE: 'CREATE_EMPLOYEE_MOVEMENT_TYPE',
  UPDATE_EMPLOYEE_MOVEMENT_TYPE: 'UPDATE_EMPLOYEE_MOVEMENT_TYPE',
  SOFT_DELETE_EMPLOYEE_MOVEMENT_TYPE: 'SOFT_DELETE_EMPLOYEE_MOVEMENT_TYPE',
  //#endregion 201-files

  //#region leave-management

  /** leave */
  CREATE_LEAVE: 'CREATE_LEAVE',
  UPDATE_LEAVE: 'UPDATE_LEAVE',
  APPROVE_LEAVE: 'APPROVE_LEAVE',
  REJECT_LEAVE: 'REJECT_LEAVE',
  CANCEL_LEAVE: 'CANCEL_LEAVE',
  SOFT_DELETE_LEAVE: 'SOFT_DELETE_LEAVE',
  FIND_LEAVE_BY_ID: 'FIND_LEAVE_BY_ID',
  FIND_LEAVE_PAGINATED_LIST: 'FIND_LEAVE_PAGINATED_LIST',
  FIND_LEAVE_REQUESTS: 'FIND_LEAVE_REQUESTS',
  FIND_PENDING_LEAVE_REQUESTS: 'FIND_PENDING_LEAVE_REQUESTS',

  /** leave_type */
  CREATE_LEAVE_TYPE: 'CREATE_LEAVE_TYPE',
  UPDATE_LEAVE_TYPE: 'UPDATE_LEAVE_TYPE',
  SOFT_DELETE_LEAVE_TYPE: 'SOFT_DELETE_LEAVE_TYPE',
  FIND_LEAVE_TYPE_BY_ID: 'FIND_LEAVE_TYPE_BY_ID',
  /** leave_policy */
  CREATE_LEAVE_POLICY: 'CREATE_LEAVE_POLICY',
  UPDATE_LEAVE_POLICY: 'UPDATE_LEAVE_POLICY',
  SOFT_DELETE_LEAVE_POLICY: 'SOFT_DELETE_LEAVE_POLICY',
  FIND_LEAVE_POLICY_BY_ID: 'FIND_LEAVE_POLICY_BY_ID',
  ACTIVATE_LEAVE_POLICY: 'ACTIVATE_LEAVE_POLICY',
  RETIRE_LEAVE_POLICY: 'RETIRE_LEAVE_POLICY',

  /** leave_balance */
  CREATE_LEAVE_BALANCE: 'CREATE_LEAVE_BALANCE',
  UPDATE_LEAVE_BALANCE: 'UPDATE_LEAVE_BALANCE',
  SOFT_DELETE_LEAVE_BALANCE: 'SOFT_DELETE_LEAVE_BALANCE',
  FIND_LEAVE_BALANCE_BY_ID: 'FIND_LEAVE_BALANCE_BY_ID',
  FIND_LEAVE_BALANCE_BY_EMPLOYEE_YEAR: 'FIND_LEAVE_BALANCE_BY_EMPLOYEE_YEAR',
  FIND_LEAVE_BALANCE_BY_LEAVE_TYPE: 'FIND_LEAVE_BALANCE_BY_LEAVE_TYPE',
  CLOSE_LEAVE_BALANCE: 'CLOSE_LEAVE_BALANCE',
  RESET_LEAVE_BALANCES_FOR_YEAR: 'RESET_LEAVE_BALANCES_FOR_YEAR',
  GENERATE_ANNUAL_LEAVE_BALANCES: 'GENERATE_ANNUAL_LEAVE_BALANCES',

  /** leave_cycle */
  SETUP_LEAVE_CYCLES: 'SETUP_LEAVE_CYCLES',
  CREATE_LEAVE_CYCLE: 'CREATE_LEAVE_CYCLE',
  CLOSE_LEAVE_CYCLE: 'CLOSE_LEAVE_CYCLE',
  FIND_LEAVE_CYCLE_BY_ID: 'FIND_LEAVE_CYCLE_BY_ID',

  /** holiday */
  CREATE_HOLIDAY: 'CREATE_HOLIDAY',
  UPDATE_HOLIDAY: 'UPDATE_HOLIDAY',
  SOFT_DELETE_HOLIDAY: 'SOFT_DELETE_HOLIDAY',
  FIND_HOLIDAY_BY_ID: 'FIND_HOLIDAY_BY_ID',
  FIND_HOLIDAYS_BY_DATE_RANGE: 'FIND_HOLIDAYS_BY_DATE_RANGE',
  FIND_HOLIDAY_BY_YEAR: 'FIND_HOLIDAY_BY_YEAR',

  //#endregion leave-management

  //#region document-management

  /** document_type */
  CREATE_DOCUMENT_TYPE: 'CREATE_DOCUMENT_TYPE',
  UPDATE_DOCUMENT_TYPE: 'UPDATE_DOCUMENT_TYPE',
  SOFT_DELETE_DOCUMENT_TYPE: 'SOFT_DELETE_DOCUMENT_TYPE',

  /** document */
  CREATE_DOCUMENT: 'CREATE_DOCUMENT',
  UPDATE_DOCUMENT: 'UPDATE_DOCUMENT',
  SOFT_DELETE_DOCUMENT: 'SOFT_DELETE_DOCUMENT',

  /** memorandum_document */
  CREATE_MEMORANDUM_DOCUMENT: 'CREATE_MEMORANDUM_DOCUMENT',
  UPDATE_MEMORANDUM_DOCUMENT: 'UPDATE_MEMORANDUM_DOCUMENT',

  //#endregion document-management

  //#region upload

  /** upload */
  UPLOAD_FILE: 'UPLOAD_FILE',
  GET_FILE_URL: 'GET_FILE_URL',

  //#endregion upload
};
