@token = 
@host = http://localhost:3220/api/v1/department

###
# CREATE
POST {{host}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "desc1": "test",
  "code": "test",
  "designation": "test"
}

###
# UPDATE 
PATCH  {{host}}/21
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "desc1": "test update",
  "code": "test update",
  "designation": "test update"
}

###
# GET 
GET  {{host}}?term=&page=1&limit=100
Content-Type: application/json
Authorization: Bearer {{token}}


###
# GET COMBOBOX 
GET  {{host}}/combobox
Content-Type: application/json
Authorization: Bearer {{token}}

###
# ARCHIVE
PATCH  {{host}}/21/archive
Content-Type: application/json
Authorization: Bearer {{token}}

###
# UNARCHIVE
PATCH  {{host}}/21/unarchive
Content-Type: application/json
Authorization: Bearer {{token}}
