@token = 
@host = http://localhost:3220/api/v1/province

###
# CREATE
POST {{host}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "desc1": "test"
}

###
# UPDATE 
PATCH  {{host}}/86
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "desc1": "test update"
}

###
# GET 
GET  {{host}}?term=test&page=1&limit=100
Content-Type: application/json
Authorization: Bearer {{token}}


###
# GET COMBOBOX 
GET  {{host}}/combobox
Content-Type: application/json
Authorization: Bearer {{token}}

###
# ARCHIVE
PATCH  {{host}}/86/archive
Content-Type: application/json
Authorization: Bearer {{token}}

###
# UNARCHIVE
PATCH  {{host}}/86/unarchive
Content-Type: application/json
Authorization: Bearer {{token}}
